name: Test Node Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Create sample files
        run: |
          mkdir -p src
          echo "console.log('Hello World');" > src/sample.js
          echo "{ \"key\": \"value\" }" > src/sample.json
          echo "<html><body>Hello</body></html>" > src/sample.html
          echo "This is a sample instruction file. use the contents ONLY within the src path, do not write over index.js. always write to a new folder instead of the relative one unless specified, these isntructions state to use the src path" > instructions.txt

      - name: Set up OpenAI API Key
        run: echo "OPENAI_API_KEY=ssk-wJH_jXT2gKYr__eXZZZSxUl8w8e5dwWP2d4I7St0tzT3BlbkFJyKl10GrYOmB6_wF337jRQj2aBfi3R4_HnJZfAV-ggA" > .env
        
      - name: Clean up previous test outputs
        run: |
          rm -f transformed.out
          rm -f src/sample.min.js src/sample.min.json src/sample.min.html

      - name: Run script with inline instructions
        run: |
          node index.js "minify all files in the src directory"

      - name: Run script with file input
        run: |
          node index.js "minify all files in the src directory" -f instructions.txt

      - name: Rename output files to avoid overwriting
        run: |
          mv src/sample.js src/sample.min.js
          mv src/sample.json src/sample.min.json
          mv src/sample.html src/sample.min.html

      - name: Check output files
        run: |
          cat transformed.out
          cat src/sample.min.js
          cat src/sample.min.json
          cat src/sample.min.html
